-- DB usage growth snapshots for monitoring table/database growth over time.
--
-- This enables computing growth deltas/rates (e.g. bytes/day) for the biggest
-- tables as well as total database size, without needing any external system.
--
-- Design notes:
-- - We only allow inserts/selects via SECURITY DEFINER function executed by service_role.
-- - Snapshotting is lightweight: a few rows per call (top N tables).
-- - We de-duplicate snapshots by skipping inserts if a snapshot was captured recently.

CREATE TABLE IF NOT EXISTS public.admin_db_usage_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  database_bytes bigint not null,
  schema_name text not null,
  table_name text not null,
  total_bytes bigint not null,
  table_bytes bigint not null,
  index_bytes bigint not null,
  toast_bytes bigint not null,
  row_estimate bigint not null default 0
);

CREATE INDEX IF NOT EXISTS admin_db_usage_snapshots_captured_at_idx
  ON public.admin_db_usage_snapshots (captured_at desc);

CREATE INDEX IF NOT EXISTS admin_db_usage_snapshots_table_idx
  ON public.admin_db_usage_snapshots (schema_name, table_name, captured_at desc);

-- Lock down direct access (admin API calls via service_role only).
ALTER TABLE public.admin_db_usage_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.admin_db_usage_snapshots FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.admin_db_usage_snapshots TO service_role;

DROP POLICY IF EXISTS "service_role_only" ON public.admin_db_usage_snapshots;
CREATE POLICY "service_role_only"
  ON public.admin_db_usage_snapshots
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Optional retention helper (not invoked automatically).
CREATE OR REPLACE FUNCTION public.admin_db_usage_prune_snapshots(p_keep_days integer DEFAULT 30)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  _keep interval := make_interval(days => GREATEST(1, COALESCE(p_keep_days, 30)));
BEGIN
  DELETE FROM public.admin_db_usage_snapshots
  WHERE captured_at < now() - _keep;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_db_usage_prune_snapshots(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_db_usage_prune_snapshots(integer) TO service_role;

